const translations = {
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_types: "Construction Types",
        nav_disciplines: "Disciplines",
        nav_contact: "Contact",
        moto: "Strong in steel and concrete",
        about: "About Us",
        about_1: "Joy Engineering is a structural engineering firm founded in 2018 by Ing. Arif Akdag as a side activity. This stemmed from a strong passion for stability studies, combined with an active role in education and a career in employment.",
        about_2: "With over 25 years of experience in carrying out stability studies, we have specialized in the calculation of various structural constructions, including:",
        about_li1: "Reinforced and prestressed concrete (both in situ and prefab)",
        about_li2: "Floor solutions",
        about_li3: "Steel structures",
        about_li4: "Foundation techniques",
        about_3: "Thanks to our multilingual expertise, we can conduct studies in Dutch, French, English, and German. Additionally, we have extensive experience with construction studies and project monitoring in both the Netherlands and Germany.",
        about_4: "Our involvement in education remains an essential part of our professional development, while Joy Engineering focuses on providing well-thought-out and efficient stability solutions for various construction projects.",
        about_5: "We have a broad network of experts, both domestically and internationally, ensuring that no challenge is impossible for us. Do you have a question or need advice? Feel free to contact us without obligation.",
        projects_title: "Disciplines",
        projects_text: "We conduct stability studies for various types of projects, including:",
        projects_title1: "Residential Construction",
        projects_info1: "From single-family homes to apartment buildings",
        projects_title2: "Industrial Construction",
        projects_info2: "Functional and durable structures for production halls, warehouses, and offices",
        projects_title3: "Geotechnical Structures",
        projects_info3: "Retaining walls, foundations, and embankments",
        types_title: "Types of Structures",
        types_text1: "Our expertise includes the calculation and analysis of various structural constructions, including:",
        types_text2: "With broad knowledge and experience in both national and international projects, we provide reliable and efficient custom solutions.",
        type_title1: "Reinforced and Prestressed Concrete",
        type_info2: "",
        type_title2: "Steel Structures",
        type_info1: "",
        type_title3: "Wood and Hybrid Constructions",
        type_info3: "",
        type_title4: "Foundation Techniques and Geotechnical Solutions",
        type_info4: "",
        photos: "See Photos",
        office: "Office",
        phone: "Phone",
        
    },
    fr: {
        nav_home: "Accueil",
        nav_about: "À propos",
        nav_types: "Types De Construction",
        nav_disciplines: "Disciplines",
        nav_contact: "Contact",
        moto: "Solide en acier et en béton",
        about: "À Propos",
        about_1: "Joy Engineering est un bureau d'études en ingénierie structurelle, fondé en 2018 par Ing. Arif Akdag en tant qu'activité secondaire. Cette initiative est née d'une passion forte pour les études de stabilité, combinée à un rôle actif dans l'enseignement et une carrière en entreprise.",
        about_2: "Avec plus de 25 ans d'expérience dans la réalisation d'études de stabilité, nous nous sommes spécialisés dans le calcul de diverses structures de construction, notamment :",
        about_li1: "Béton armé et précontraint (coulé en place et préfabriqué)",
        about_li2: "Solutions de plancher",
        about_li3: "Structures en acier",
        about_li4: "Techniques de fondation",
        about_3: "Grâce à notre expertise multilingue, nous pouvons réaliser des études en néerlandais, français, anglais et allemand. De plus, nous avons une grande expérience des études de construction et du suivi de projet aux Pays-Bas et en Allemagne.",
        about_4: "Notre engagement dans l'enseignement reste un élément essentiel de notre développement professionnel, tandis que Joy Engineering se concentre sur la fourniture de solutions de stabilité réfléchies et efficaces pour divers projets de construction.",
        about_5: "Nous disposons d'un vaste réseau d'experts, tant au niveau national qu'international, ce qui nous permet de relever tous les défis. Vous avez une question ou besoin de conseils ? N'hésitez pas à nous contacter.",
        projects_title: "Disciplines",
        projects_text: "Nous réalisons des études de stabilité pour différents types de projets, notamment :",
        projects_title1: "Construction Résidentielle",
        projects_info1: "Des maisons individuelles aux immeubles d’appartements",
        projects_title2: "Construction Industrielle",
        projects_info2: "Structures fonctionnelles et durables pour halls de production, entrepôts et bureaux",
        projects_title3: "Structures Géotechniques",
        projects_info3: "Murs de soutènement, fondations et protections de berges",
        types_title: "Types De Constructions",
        types_text1: "Notre expertise couvre le calcul et l'analyse de diverses structures de construction, notamment :",
        types_text2: "Avec une large connaissance et une expérience dans des projets nationaux et internationaux, nous proposons des solutions fiables et efficaces adaptées à chaque besoin.",
        type_title1: "Béton Armé et Précontraint",
        type_info2: "",
        type_title2: "Structures en Acier",
        type_info1: "",
        type_title3: "Constructions en Bois et Hybrides",
        type_info3: "",
        type_title4: "Techniques de Fondation et Solutions Géotechniques",
        type_info4: "",
        photos: "Voir Les Photos",
        office: "Office",
        phone: "Téléphone",
    },
    nl: {
        nav_home: "Startpagina",
        nav_about: "Over ons",
        nav_types: "Constructie Typen",
        nav_disciplines: "Disciplines",
        nav_contact: "Contact",
        moto: "Sterk in staal en beton",
        about: "Over Ons",
        about_1: "Joy Engineering is een bouwkundig studiebureau, opgericht in 2018 door Ing. Arif Akdag als nevenactiviteit. Dit vanuit een sterke passie voor stabiliteitsstudies, gecombineerd met een actieve rol in het onderwijs en een loopbaan in dienstverband.",
        about_2: "Met meer dan 25 jaar ervaring in de uitvoering van stabiliteitsstudies hebben wij ons gespecialiseerd in de berekening van diverse bouwkundige constructies, waaronder:",
        about_li1: "Gewapend en voorgespannen beton (zowel in situ als prefab)",
        about_li2: "Vloeroplossingen",
        about_li3: "Staalconstructies",
        about_li4: "Funderingstechnieken",
        about_3: "Dankzij onze meertalige expertise kunnen wij studies uitvoeren in het Nederlands, Frans, Engels en Duits. Daarnaast hebben we ruime ervaring met bouwstudies en projectopvolging in zowel Nederland als Duitsland.",
        about_4: "De activiteiten binnen het onderwijs blijven een belangrijk onderdeel van onze professionele ontwikkeling, terwijl Joy Engineering zich richt op het leveren van doordachte en efficiënte stabiliteitsoplossingen voor diverse bouwprojecten.",
        about_5: "Wij beschikken over een breed netwerk van experts, zowel in binnen- als buitenland, waardoor geen enkele uitdaging voor ons onmogelijk is . Heeft u een vraag of wilt u advies? Neem gerust vrijblijvend contact op.",
        projects_title: "Disciplines",
        projects_text: "Wij voeren stabiliteitsstudies uit voor uiteenlopende projecten, waaronder:",
        projects_title1: "Woningbouw",
        projects_info1: "Van eengezinswoningen tot appartementsgebouwen",
        projects_title2: "Industriebouw",
        projects_info2: "Functionele en duurzame constructies voor productiehallen, loodsen en kantoren",
        projects_title3: "Geotechnische Constructies",
        projects_info3: "Keermuren, funderingen en beschoeiingen",
        types_title: "Constructie typen",
        types_text1: "Onze expertise omvat de berekening en analyse van diverse bouwkundige constructies, waaronder:",
        types_text2: "Met een brede kennis en ervaring in zowel nationale als internationale projecten zorgen wij voor betrouwbare en efficiënte oplossingen op maat.",
        type_title1: "Gewapend En Voorgespannen Beton ",
        type_info2: "",
        type_title2: "Staalstructuren",
        type_info1: "",
        type_title3: "Hout- En Hybride Constructies",
        type_info3: "",
        type_title4: "Funderingstechnieken En Geotechnische Oplossingen",
        type_info4: "",
        photos: "Zie Fotos", 
        office: "Kantoor",
        phone: "Telefoon",


    }
};

function changeLanguage(lang) {
    document.querySelectorAll("[data-lang]").forEach(element => {
        const key = element.getAttribute("data-lang");
        element.textContent = translations[lang][key];
    });

    // Save language preference
    localStorage.setItem("selectedLanguage", lang);
}

// Load saved language
document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("selectedLanguage") || "en";
    changeLanguage(savedLang);
});
